# Generated by Django 3.2.3 on 2021-06-24 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('player_id', models.IntegerField(default=0)),
                ('nationality', models.CharField(max_length=120)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('potential', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=120)),
                ('player_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.tournament')),
            ],
            options={
                'verbose_name_plural': 'Player Statistics',
            },
        ),
    ]
