# Generated by Django 3.2.4 on 2021-06-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0002_player_playerstatistic_team_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstatistic',
            name='tournament',
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='tournament',
            field=models.ManyToManyField(to='fifa.Tournament'),
        ),
    ]
